version: '3'
services:

  # Loadbalancer
  web:
    image: nginx
    container_name: web-1
    volumes:
      - ./front/conf/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - angular
    networks:
      - app-network

  # Webapp
  angular:
    image: trion/ng-cli:1.7.3
    container_name: angular
    working_dir: /app
    user: node
    volumes:
      - "./front:/app"
    ports:
      - "4200:4200"
    command: bash -c "npm install && ng serve -H 0.0.0.0 --disable-host-check"
    depends_on:
      - api
    networks:
      - app-network
  
  # Api
  api:
    image: node:7.7.2-alpine
    container_name: api-node
    ports:
      - 3000:3000
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    depends_on:
      - mongodb
    command: sh -c "cd back; npm i && npm start"
    networks:
      - app-network
  
  
  # MongoDB
  mongodb:
    image: mongo
    container_name: api-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

